name: CI vers Docker Hub

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Construire l'image Docker
      run: docker build . --file Dockerfile --tag mon-image-docker:$(date +%s)
    - name: Se connecter au registre de conteneurs GitHub
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    - name: Pousser vers le registre de conteneurs GitHub
      run: docker push ghcr.io/${{ github.repository_owner }}/docker-image:$(date +%s)
